{% set build = 0 %}
{% set strbuild = "build_" + build|string %}
{% set version = "1.0.0" %}

package:
  name: cardinal-nekrs
  version: {{ version }}

source:
  - path: ../../contrib/nekRS

build:
  number: {{ build }}
  string: {{ strbuild }}
  skip: true  # [win]
  script_env:
    - MOOSE_JOBS
  run_exports:
    - {{ pin_subpackage('cardinal-nekrs', max_pin='x.x') }}

requirements:
  build:
    - {{ moose_libmesh }}
    - cmake
    - pkg-config
  run:
    - {{ moose_libmesh }}

test:
  requires:
    - {{ moose_mpich }}
  commands:
    - nekrs --help

about:
  home: https://github.com/Nek5000/nekRS
  license: GNU
  license_file: LICENSE
  summary: >
    nekRS is an open-source Navier Stokes solver based on the spectral element method targeting
    classical processors and accelerators like GPUs. The code started as an fork of libParanumal in
    2019. For API portable programming OCCA is used.

extra:
  recipe-maintainers:
    - milljm
