{% set build = 0 %}
{% set strbuild = "build_" + build|string %}
{% set version = "1.0.0" %}

package:
  name: cardinal-dagmc
  version: {{ version }}

# Bring cardinal/.git/modules so pyne compiles (pyne needs to perform a `git rev-parse HEAD`)
source:
  - path: ../../contrib/DAGMC
    folder: cardinal/contrib/DAGMC
  - path: ../../.git/modules/contrib/DAGMC
    folder: cardinal/.git/modules/contrib/DAGMC

build:
  number: {{ build }}
  string: {{ strbuild }}
  skip: true  # [win]
  script_env:
    - MOOSE_JOBS
  run_exports:
    - {{ pin_subpackage('cardinal-dagmc', max_pin='x.x') }}

requirements:
  build:
    - {{ cardinal_moab }}
    - cmake
    - pkg-config
  run:
    - {{ cardinal_moab }}

test:
  requires:
    - {{ cardinal_moab }}
  commands:
    - ray_fire_test -h

about:
  home: https://svalinn.github.io/DAGMC/
  license: BSD
  license_file: cardinal/contrib/DAGMC/LICENSE.txt
  summary: >
    Direct Accelerated Geometry Monte Carlo (DAGMC) is a software package that allows users to
    perform Monte Carlo radiation transport directly on CAD models.

extra:
  recipe-maintainers:
    - milljm
