diff --git a/Makefile b/Makefile
index c0810933..9132bd57 100644
--- a/Makefile
+++ b/Makefile
@@ -281,15 +281,6 @@ endif
 # External apps
 # ======================================================================================
 
-# libmesh_CXX, etc, were defined in build.mk
-export CXX := $(libmesh_CXX)
-export CC  := $(libmesh_CC)
-export FC  := $(libmesh_F90)
-export FFLAGS := $(libmesh_FFLAGS)
-export CFLAGS := $(libmesh_CFLAGS)
-export CXXFLAGS := $(libmesh_CXXFLAGS)
-export CPPFLAGS := $(libmesh_CPPFLAGS)
-export LDFLAGS := $(libmesh_LDFLAGS)
 export LIBS := $(libmesh_LIBS)
 
 export CARDINAL_DIR
@@ -351,13 +342,16 @@ endif
 ADDITIONAL_LIBS := -L$(CARDINAL_DIR)/lib $(CC_LINKER_SLFLAG)$(CARDINAL_DIR)/lib
 
 ifeq ($(ENABLE_NEK), yes)
-  ADDITIONAL_LIBS += -L$(NEKRS_LIBDIR) -lnekrs -locca $(CC_LINKER_SLFLAG)$(NEKRS_LIBDIR)
+  ADDITIONAL_LIBS += -L$(NEKRS_LIBDIR) -lnekrs-hypre -lnekrs-hypre-device -lnekrs -locca $(CC_LINKER_SLFLAG)$(NEKRS_LIBDIR)
 endif
 
 ifeq ($(ENABLE_OPENMC), yes)
-  ADDITIONAL_LIBS += -L$(OPENMC_LIBDIR) -lopenmc -lhdf5_hl $(CC_LINKER_SLFLAG)$(OPENMC_LIBDIR)
+  ADDITIONAL_LIBS += -L$(OPENMC_LIBDIR) -luwuw -ldagmc -lpyne_dagmc -lMOAB -lopenmc -lhdf5_hl $(CC_LINKER_SLFLAG)$(OPENMC_LIBDIR)
 endif
 
+# Need correct libpng16 used by libmesh-vtk package
+ADDITIONAL_LIBS += -L$(PETSC_DIR)/lib -lpng16
+
 include            $(FRAMEWORK_DIR)/app.mk
 
 # app_objects are defined in moose.mk and built according to the rules in build.mk
