{% set build = 0 %}
{% set strbuild = "build_" + build|string %}
{% set version = "1.0.0" %}

package:
  name: cardinal
  version: {{ version }}

source:
  - path: ../../../cardinal

build:
  number: {{ build }}
  string: {{ strbuild }}
  skip: true  # [win]
  script_env:
    - MOOSE_JOBS
  run_exports:
    - {{ pin_subpackage('cardinal', max_pin='x.x') }}

requirements:
  build:
    - {{ cardinal_openmc }}
    - pkg-config
  run:
    - {{ cardinal_openmc }}

about:
  home: https://cardinal.cels.anl.gov/index.html
  license: GNU
  license_file: LICENSE
  summary: >
    Cardinal is a wrapping of the spectral element code CFD NekRS and the Monte Carlo radiation
    transport code OpenMC as a MOOSE application. Cardinal is intended for providing high-resolution
    thermal-hydraulics and particle transport feedback to MOOSE multiphysics simulations.

extra:
  recipe-maintainers:
    - milljm
