{% set build = 2 %}
{% set strbuild = "build_" + build|string %}
{% set version = "1.0.0" %}

package:
  name: cardinal
  version: {{ version }}

source:
  - path: ../../../cardinal
  - path: ../../.git/modules/contrib/DAGMC
    folder: .git/modules/contrib/DAGMC
  - path: ../../.git/modules/contrib/openmc
    folder: .git/modules/contrib/openmc
  - path: ../../.git/modules/contrib/nekRS
    folder: .git/modules/contrib/nekRS
  - path: ../../.git/modules/contrib/moab
    folder: .git/modules/contrib/moab
  - path: ../../.git/modules/contrib/moose
    folder: .git/modules/contrib/moose
  - patches:
      - Makefile.patch
      - config_nekrs.patch

build:
  number: {{ build }}
  string: {{ strbuild }}
  skip: true  # [win]
  script_env:
    - MOOSE_JOBS
  run_exports:
    - {{ pin_subpackage('cardinal', max_pin='x.x') }}

requirements:
  build:
    - {{ moose_libmesh }}
    - cmake
    - pkg-config
    - python 3.10
  run:
    - {{ moose_libmesh }}

test:
  requires:
    - {{ moose_libmesh }}
  commands:
    - cardinal-opt --help
    - nekrs --help
    - openmc --help
    - ray_fire_test -h
    - mbhonodes -h

about:
  home: https://cardinal.cels.anl.gov/index.html
  license: GNU
  license_file: LICENSE
  summary: >
    Cardinal is a wrapping of the spectral element code CFD NekRS and the Monte Carlo radiation
    transport code OpenMC as a MOOSE application. Cardinal is intended for providing high-resolution
    thermal-hydraulics and particle transport feedback to MOOSE multiphysics simulations.

extra:
  recipe-maintainers:
    - milljm
