{% set build = 0 %}
{% set strbuild = "build_" + build|string %}
{% set version = "1.0.0" %}

package:
  name: cardinal-openmc
  version: {{ version }}

source:
  - path: ../../contrib/openmc

build:
  number: {{ build }}
  string: {{ strbuild }}
  skip: true  # [win]
  script_env:
    - MOOSE_JOBS
  run_exports:
    - {{ pin_subpackage('cardinal-openmc', max_pin='x.x') }}

requirements:
  build:
    - {{ cardinal_dagmc }}
    - cmake
    - pkg-config
  run:
    - {{ cardinal_dagmc }}

test:
  requires:
    - {{ cardinal_dagmc }}
  commands:
    - openmc --help

about:
  home: https://github.com/Nek5000/nekRS
  license: GNU
  license_file: LICENSE
  summary: >
    The OpenMC project aims to provide a fully-featured Monte Carlo particle transport code based on
    modern methods. It is a constructive solid geometry, continuous-energy transport code that uses
    HDF5 format cross sections. The project started under the Computational Reactor Physics Group at
    MIT.

extra:
  recipe-maintainers:
    - milljm
